### ISSUE TITLE
Css issue

### ISSUE THREAD

**Issue by aeq-dev** [aymanalhattami/filament-date-scopes-filter#1]
Hi,
I'm getting this design : 
![Screenshot from 2023-11-24 11-48-19](https://github.com/aymanalhattami/filament-date-scopes-filter/assets/81385994/e891f2d2-8424-48cd-827e-1ab3cec1b050)

**Comment by aymanalhattami** [comment]
It will be fixed

**Comment by aymanalhattami** [comment]
fixed on version [1.0.1](https://github.com/aymanalhattami/filament-date-scopes-filter/releases/tag/1.0.1)

**Comment by aeq-dev** [comment]
Thanks
